////

  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

////

include::_settings.adoc[]
:presenter_name: Your Name Here
:presenter_company: Apache Software Foundation

== ComDev Working Groups

[%step]
* Why we made them.
* What they're for?
* Which ones have we created?
* How to get involved.

== A bit about ComDev

* What it is
* What it is not

--
* ComDev exists to help projects build their communties
* Yes, projects should do this themselves, but having common practices and tools lowers the barrier
* ComDev is a PMC - a peer to other PMCs. It does *not* have authority over other PMCs.
--

== ComDev is you, you are ComDev

ComDev does not do this work *for* you. It's a place for everyone to
collaborate on best practices and tools that span all projects.


