= Repository Inspection Report
Apache Training
generated by <repo-doc-analysis tool>
:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:toc:
// Uncomment next line to add a title page (or set doctype to book)
:title-page:
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter

<<<

== Summary

=== Overview
NUMBER of values: 8

<<<

=== Details



## Q1 :: What is the projects title?

### Answer:
I don't know.

### Sources:

  
#### All relevant sources:
* ../docs-main/kafka/CONTRIBUTING.md
* ../docs-main/kafka/README.md
* ../docs-main/kafka/PULL_REQUEST_TEMPLATE.md


---




## Q2 :: What is the projects description?

### Answer:
I don't know.

### Sources:

  
#### All relevant sources:
* ../docs-main/kafka/README.md
* ../docs-main/kafka/PULL_REQUEST_TEMPLATE.md


---




## Q4 :: How do I use the project?

### Answer:
To use the project, you can follow these steps:

1. Make sure you have Java installed on your system. You can download Java from the [Oracle website](http://www.oracle.com/technetwork/java/javase/downloads/index.html).

2. Clone the Kafka project repository.

3. Install specific projects to the local Maven repository by running the following command:
   ```
   ./gradlew -PskipSigning=true :streams:publishToMavenLocal
   ```
   If you need to specify the Scala version, you can use the `-PscalaVersion=2.13` flag.

4. Build the test jar by running the following command:
   ```
   ./gradlew testJar
   ```

5. Run code quality checks using the following commands:
   - Checkstyle: 
     ```
     ./gradlew checkstyleMain checkstyleTest
     ```
     The checkstyle warnings will be found in `reports/checkstyle/reports/main.html` and `reports/checkstyle/reports/test.html` files.
   - Spotbugs:
     ```
     ./gradlew spotbugsMain spotbugsTest -x test
     ```
     The spotbugs warnings will be found in `reports/spotbugs/main.html` and `reports/spotbugs/test.html` files.

6. If you want to run JMH microbenchmarks, refer to the [jmh-benchmarks/README.md](https://github.com/apache/kafka/blob/trunk/jmh-benchmarks/README.md) file for instructions.

7. To see a list of all available Gradle tasks, run the following command:
   ```
   ./gradlew tasks
   ```

8. If you want to build the project for your IDE, you can use the following commands:
   - For Eclipse:
     ```
     ./gradlew eclipse
     ```
   - For IntelliJ IDEA:
     ```
     ./gradlew idea
     ```

9. If you want to publish the jar for all versions of Scala and for all projects to Maven, you can use the following command:
   ```
   ./gradlewAll publish
   ```
   Alternatively, you can use `./gradlewAll uploadArchives` for backwards compatibility. Make sure to set the required variables in your `gradle.properties` file.

For more details and information on contributing to the project, you can visit the [Apache Kafka website](https://kafka.apache.org) and review the documentation provided.

### Sources:

  
#### All relevant sources:
* ../docs-main/kafka/CONTRIBUTING.md
* ../docs-main/kafka/README.md


---




## Q5 :: Where do I get the documentation from?

### Answer:
You can find the documentation for Apache Kafka on the project's website at [https://kafka.apache.org](https://kafka.apache.org). The documentation provides details on various aspects of Kafka, including installation, configuration, usage, and contribution guidelines.

### Sources:

  
#### All relevant sources:
* ../docs-main/kafka/CONTRIBUTING.md
* ../docs-main/kafka/README.md


---




## Q6 :: How can I contribute?

### Answer:
To contribute to Apache Kafka, you can follow these steps:

1. Review the [Contributing](https://kafka.apache.org/contributing.html) and [Contributing Code Changes](https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes) pages to understand the requirements before creating a pull request.

2. Make sure that your contribution is your original work and that you license it to the project under the project's open source license. By submitting any copyrighted material via pull request, email, or other means, you agree to license the material under the project's open source license and warrant that you have the legal authority to do so.

3. If you have any thoughts or patches, you can share them with the Apache Kafka community. You can reach out to the community [on the Apache mailing lists](http://kafka.apache.org/contact.html).

For more detailed instructions on how to contribute, you can refer to the [Contribution](https://kafka.apache.org/contributing.html) page.



### Sources:
../docs-main/kafka/CONTRIBUTING.md ../docs-main/kafka/README.md
  
#### All relevant sources:
* ../docs-main/kafka/CONTRIBUTING.md
* ../docs-main/kafka/README.md
* ../docs-main/kafka/PULL_REQUEST_TEMPLATE.md


---




## Q7 :: What license is used?

### Answer:
The project is licensed under an open source license. By contributing code, you affirm that the contribution is your original work and that you license the work to the project under the project's open source license. The specific details of the open source license are not mentioned in the provided context.

### Sources:

  
#### All relevant sources:
* ../docs-main/kafka/CONTRIBUTING.md
* ../docs-main/kafka/README.md
* ../docs-main/kafka/PULL_REQUEST_TEMPLATE.md


---




## Q8 :: How does the roadmap look like?

### Answer:
I don't know.

### Sources:

  
#### All relevant sources:
* ../docs-main/kafka/CONTRIBUTING.md
* ../docs-main/kafka/README.md
* ../docs-main/kafka/PULL_REQUEST_TEMPLATE.md


---




## Q9 :: Who are the authors?

### Answer:
I don't know.

### Sources:

  
#### All relevant sources:
* ../docs-main/kafka/raft/README.md
* ../docs-main/kafka/CONTRIBUTING.md
* ../docs-main/kafka/README.md
* ../docs-main/kafka/PULL_REQUEST_TEMPLATE.md


---




