////

  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

////

include::_settings.adoc[]
:presenter_name: Justin Mclean
:presenter_company: Apache Software Foundation

=== Navigating the ASF Incubator Process
TODO image and title

== Who am I?
* V.P. Apache Incubator
* Freelance developer - programming for 30 years
* Incubator PMC plus a few others
* Apache member
* Mentor of several Apache projects including Apache Dubbo
* Reviewed 350+ incubator releases at Apache

== What is the ASF?
* World’s largest Open Source Foundation
* A neutral space where independent projects can prosper
* Creates open source software for the public good free of charge
* Business friendly Apache License 2.0
* 6500+ committers, 700+ members, 196 PMCs, 50+ podlings

== What is the Apache Incubator?
* Where communities come to learn the Apache Way
* Likes existing projects with a community around them
* Main entry point for new projects
