////

  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

////
:revealjs_progress: true
:revealjs_slidenumber: true

== What is the Apache Ignite?
Ignite™ is a memory-centric distributed database, caching, and processing platform

2 major use-cases

IMDG

- Stores entries in-memory
- Need external store
- Caching data

IMDB

- Ignite Native Persistence
- Collocated Processing

Combined usage

Persistence per enabled per cache
(actually, memory region)

== Nodes
Two (major) type of nodes

- Server node
Can store data, execute compute jobs
Usually, standalone JVM

- Client node
Used to connect to the cluster