////

  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

////
:revealjs_progress: true
:revealjs_slidenumber: true
:sourcedir: ../java

== What is the Apache Ignite?
Ignite™ is a memory-centric distributed database, caching, and processing platform.

2 major use-cases
- In-Memory Data Grid
- Memory Centric Database

== IMDG
IMDG = Stores data (data grid) + Process data (compute grid)

- Stores entries in-memory
- Data is distributed among the nodes
- Need external store
- Collocated Processing = code goes to data.

== IMDB
In Memory (or memory-centric) database.

- Memory region can be configured with enabled persistence
- Ignite Native Persistence since V2.1
- Scalable: Each node stores its data.

Ignite can be used in combined mode:
Persistence is enabled per memory region

== Why you may need Apache Ignite™
- To speed up a slow traditional database by caching entries
- To cache data from remote sources (REST, SOAP, any other network protocols)
- For projects from scratch: Build a scalable solution with horizontal scaling
- To remove a computational load from overloaded database
- Avoid single point of failure by changing traditional database to cluster

== Nodes
Apache Ignite cluster consists from two (major) type of nodes

- Server node
* Can store data
* execute compute jobs
* Usually, standalone JVM

- Client node
* Used to connect to the cluster

== Starting a server node

[source,java]
----
include::{sourcedir}/example/StartServerNode.java[tags=contains,indent=0]
----